apiVersion: apps/v1
kind: Deployment
metadata:
  name: detect-reused-refresh-token
  labels:
    app: detect-reused-refresh-token-app
  namespace: token-handler
spec:
  selector:
    matchLabels:
      app: detect-reused-refresh-token-app
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: detect-reused-refresh-token-app
    spec:
      containers:
      - name: detect-reused-refresh-token-app
<<<<<<< HEAD
        image: conano/detect-reused-refresh-token-handler:latest        
        envFrom:
        - secretRef:
            name: detect-reused-refresh-token-secret
=======
        image: conano/detect-reused-refresh-token-handler:0.0.1-4
>>>>>>> 9dbbe92dc731c8a4d1ad2469551a7951f5ee2db6
        imagePullPolicy: IfNotPresent        
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"
